version: '3.4'

services:
    customerdb:
        image: mcr.microsoft.com/mssql/server

    cachedb:
        image: redis

    repositorywithcaching.webapi:
        image: ${DOCKER_REGISTRY-}repositorywithcachingwebapi
        build:
            context: .
            dockerfile: RepositoryWithCaching/RepositoryWithCaching.WebApi/Dockerfile
